name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Set up Clojure CLI tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1139

      - name: Build the optimized release using shadow-cljs
        run: npx shadow-cljs release app

      - name: Determine Deployment Branch
        id: get-branch
        run: echo "branch=$(if [ '${{ github.ref_name }}' == 'main' ]; then echo 'gh-pages'; else echo 'gh-pages-dev'; fi)" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/app
          publish_branch: ${{ env.branch }}












